---
- name: Install and configure Datadog Agent
  hosts: webservers
  become: yes
  vars_files:
    - group_vars/vault.yml
  tasks:
    - name: Install Datadog collection
      ansible.builtin.command: ansible-galaxy collection install datadog.dd
      delegate_to: localhost

    - name: Import Datadog Agent role
      import_role:
        name: datadog.dd.agent
      vars:
        datadog_api_key: "{{ vault_datadog_api_key }}"
        datadog_site: "datadoghq.com"  # или другой регион
        datadog_checks:
          http_check:
            init_config:
            instances:
              - name: "Redmine Health Check"
                url: "http://localhost:{{ redmine_port }}"
                collect_response_time: true
                check_certificate_expiration: false
                tags:
                  - "service:redmine"
