---
- name: "Prepare servers with Docker and dependencies"
  hosts: all
  become: true
  tasks:
    - name: Install Python and pip using apt
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: true

    - name: Ensure pip is installed
      ansible.builtin.command: python3 -m ensurepip
      args:
        creates: /usr/bin/pip3

  roles:
    - geerlingguy.docker
