---
- name: Deploy Redmine with MySQL using Docker and Ansible
  hosts: webservers
  become: yes
  vars_files:  
    - ansible/group_vars/vault.yml  
  vars:
    mysql_root_password: "{{ vault_mysql_root_password }}"
    redmine_db_password: "{{ vault_redmine_db_password }}"
    redmine_secret_key_base: "{{ vault_redmine_secret_key_base }}"
    redmine_data_dir: "/opt/redmine/data"
    mysql_data_dir: "/opt/redmine/mysql"
        
  tasks:
    - name: Debug variables
      debug:
        msg:
          - "mysql_root_password: {{ mysql_root_password }}"
          - "vault_mysql_root_password: {{ vault_mysql_root_password }}"
      
    - name: Ensure directories for data persistence exist
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0750'
      loop:
        - "{{ redmine_data_dir }}"
        - "{{ mysql_data_dir }}"

    - name: Create a custom Docker network if it doesn't exist
      docker_network:
        name: redmine_network
        driver: bridge
        state: present

    - name: Pull MySQL image
      docker_image:
        name: mysql:8.0
        source: pull

    - name: Start MySQL container
      docker_container:
        name: redmine_mysql
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: redmine
          MYSQL_USER: redmine
          MYSQL_PASSWORD: "{{ redmine_db_password }}"
        volumes:
          - "{{ mysql_data_dir }}:/var/lib/mysql"
        networks:
          - name: redmine_network
        restart_policy: always

    - name: Pull Redmine image
      docker_image:
        name: redmine:latest
        source: pull

    - name: Сгенерировать .env файл для Redmine
      ansible.builtin.template:
        src: ansible/templates/redmine.env.j2
        dest: /opt/redmine/.env
        mode: '0640'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Start Redmine container
      docker_container:
        name: redmine_app
        image: redmine:latest
        ports:
          - "{{ redmine_port }}:3000"
        env_file: /opt/redmine/.env
        volumes:
          - "{{ redmine_data_dir }}:/usr/src/redmine/files"
        networks:
          - name: redmine_network
        restart_policy: always